[package]
name = "config_file"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
log = { workspace = true }
serde_yaml = { workspace = true }
merge = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
